version: '3.8'

services:
  translate:
    build: ./translate
    ports:
      - 8000:8000
    volumes:
      - ./translate:/app

  mule:
    image: codingtony/mule
    ports:
      - "8081:8081"
    restart: always
    environment:
      - MULE_ENV=dev
    volumes:
      - ./mulesoft:/opt/mule/app
