version: '3.8'

services:
  translate:
    build: translate
    ports:
      - 8000:8000
    volumes:
      - ./translate:/app

  mule:
    image: wslph/mule:4.4.0-20220321-ee-2022-07-14
    ports:
      - "8081:8081"
    depends_on:
      - translate
    restart: always
    volumes:
      - ./mulesoft/compiled_mulesoft:/opt/mule/apps/isi_working
    environment:
      - MULE_ENV=dev

  react:
    build: frontend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - "./frontend:/app"

  django:
    build: backend
    ports:
      - "8001:8000"
    restart: always
    volumes:
      - "./backend:/app"
    env_file:
      - ./backend/.env
