version: '3.8'

services:
  translate:
    build: translate
    ports:
      - 8000:8000
    volumes:
      - ./translate:/app

  mule:
    build: mulesoft
    ports:
      - 8081:8081
    depends_on:
      - translate
    restart: always
    volumes:
      - ./mulesoft/apps:/opt/mule/apps
    environment:
      - MULE_ENV=dev

  react:
    build: frontend
    ports:
      - 3000:3000
    depends_on:
      - django
    restart: always
    volumes:
      - ./frontend:/app

  django:
    build: backend
    ports:
      - 8001:8001
    restart: always
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
