version: '3.8'

services:
  translate:
    build: translate
    ports:
      - 8000:8000
    volumes:
      - ./translate:/app

  mule:
    image: wslph/mule:4.4.0-ee
    ports:
      - 8081:8081
    depends_on:
      - translate
    restart: always
    volumes:
      - ./mulesoft/apps:/opt/mule/apps
      - ./mulesoft/compiled_mulesoft:/opt/mule/compiled_mulesoft
      - ./mulesoft/logs:/opt/mule/am/logs
    environment:
      - MULE_ENV=dev

  react:
    build: frontend
    ports:
      - 3000:3000
    depends_on:
      - django1
    restart: always
    volumes:
      - ./frontend:/app

  django1:
    build: backend
    ports:
      - 8001:8000
    restart: always
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SECRET_KEY=very_secret_key
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=app.settings1


  django2:
    build: backend
    ports:
      - 8002:8000
    restart: always
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SECRET_KEY=very_secret_key
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=app.settings2
